/*
 * PlayerPanel.java
 *
 * Created on July 1, 2005, 8:58 AM
 */

package org.invade;

/**
 *
 * @author  jcrosm
 */
public class PlayerPanel extends javax.swing.JPanel {
    
    private Player player = null;
    
    /** Creates new form PlayerPanel */
    public PlayerPanel() {
        initComponents();
    }
    
    public Player getPlayer() {
        return player;
    }
    
    public void setPlayer(String currencyName, Player player) {        
        if( player != null ) {
            this.player = player;
            nameLabel.setText(player.getName());
            nameLabel.setForeground(player.getColor());            
            energyLabel.setText(currencyName + ":  " + player.getEnergy());
            energyLabel.setVisible(currencyName != null);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        nameLabel = new javax.swing.JLabel();
        energyLabel = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        nameLabel.setText("Player");
        nameLabel.setAlignmentX(0.5F);
        add(nameLabel);

        energyLabel.setText("Energy");
        energyLabel.setAlignmentX(0.5F);
        add(energyLabel);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel energyLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
    
}
