/*
 * CommandCardDisplay.java
 *
 * Created on July 28, 2005, 3:58 PM
 */

package org.invade.commandcards;

import org.invade.Board;
import org.invade.SpecialUnit;
import org.invade.WindowCenteringUtility;

/**
 *
 * @author  jcrosm
 */
public class CommandCardDisplay extends javax.swing.JDialog {
        
    public CommandCardDisplay(java.awt.Frame parent, AbstractCommandCard card) {
        super(parent);
        
        initComponents();
        
        nameLabel.setText(card.getName());
        nameLabel.setForeground(card.getRequiredCommander().getColor());
        nameLabel.setIcon(card.getRequiredCommander().getIcon());
        powerUpLabel.setText("Power up:  " + card.getPowerUpCost());
        playWhenText.setText(card.getWhenString());
        descriptionText.setText(card.getDescriptionString());
        
        setTitle(card.getName(true, false));
        
        WindowCenteringUtility.center(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        powerUpLabel = new javax.swing.JLabel();
        playWhenText = new javax.swing.JTextArea();
        descriptionText = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Card");
        setModal(true);
        setResizable(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(240, 320));
        nameLabel.setFont(new java.awt.Font("SansSerif", 1, 14));
        nameLabel.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(nameLabel, gridBagConstraints);

        powerUpLabel.setFont(new java.awt.Font("SansSerif", 0, 12));
        powerUpLabel.setText("Power up");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 20, 2);
        jPanel1.add(powerUpLabel, gridBagConstraints);

        playWhenText.setEditable(false);
        playWhenText.setFont(new java.awt.Font("SansSerif", 0, 12));
        playWhenText.setLineWrap(true);
        playWhenText.setWrapStyleWord(true);
        playWhenText.setBorder(new javax.swing.border.EtchedBorder());
        playWhenText.setFocusable(false);
        playWhenText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel1.add(playWhenText, gridBagConstraints);

        descriptionText.setEditable(false);
        descriptionText.setFont(new java.awt.Font("SansSerif", 0, 12));
        descriptionText.setLineWrap(true);
        descriptionText.setWrapStyleWord(true);
        descriptionText.setBorder(new javax.swing.border.EtchedBorder());
        descriptionText.setFocusable(false);
        descriptionText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.75;
        jPanel1.add(descriptionText, gridBagConstraints);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(closeButton, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextArea playWhenText;
    private javax.swing.JLabel powerUpLabel;
    // End of variables declaration//GEN-END:variables
    
}
